### PR TITLE
Fix - change scope to event to add tags to sentry request

### PR DESCRIPTION
**Pull request by munroTom**
Middleware was not adding tags to events posted to Sentry as the tags were being added to the scope instead

### CODE REVIEW

**Comment by kirisanth-g** [comment]
Any update on this PR?

**Comment by vidit-sh** [comment]
@munroTom @kirisanth-g why should this be changed? I see the point of uniformity, though could you justify your change making any feature useless without this change?

**Comment by vidit-sh** [comment]
Also did you get a chance to see if this is breaking anything?

**Comment by munroTom** [comment]
@vidit-sh without this change the middleware won't attach any tags to the request when it captures an error meaning the `getTags` part of the library doesn't work at all

I've made the changes on a local copy and been running it since the creation of this PR and haven't experienced any issues

**Comment by vidit-sh** [comment]
@munroTom cud u remove package.json from commit and push changes?

**Review by vidit-sh — CHANGES_REQUESTED** [review]
Remove changes in package.json.

**Comment by munroTom** [comment]
@vidit-sh done

**Review by vidit-sh — APPROVED** [review]

**Comment by vidit-sh** [comment]
thanks @munroTom,
change merged and version published.

**Pull request merged**
